services:
  - type: web
    name: hello-world-spinner
    runtime: node
    repo: https://github.com/thebiggestcookie/hello-world-spinner
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: free
    region: oregon
